title: Abhi Hanchate
logo: /assets/headshot.png
description: >
  <p style="font-size: 14px; line-height: 1.5;">
    <h4 style="font-size: 16px;">ğŸ¯ "The future of manufacturing lies in the seamless integration of data, AI, and human ingenuity."</h4>
    <strong>â€“ and Iâ€™m dedicated to making that future a reality.</strong><br>
    Recognized as one of <strong>â€œSMEâ€™s 30 Under 30â€</strong>, I drive innovation in AI-driven smart manufacturing.
    With experience across <strong>industry and research collaborations</strong>, I transform traditional machinery into 
    secure, intelligent systems by integrating IIoT sensors, advanced sensing schemes, and manufacturing cybersecurity.
  </p>
theme: jekyll-theme-minimal
