title: Abhi Hanchate
# logo: /assets/img/headshot_circle.png
description: >
  "The future of manufacturing lies in the seamless integration of data, AI, and human ingenuity." – and I’m dedicated
  to making that future a reality. Recognized as one of “SME’s 30 Under 30”, I drive innovation in AI-driven smart
  manufacturing. With experience across industry and research collaborations, I transform traditional machinery into
  secure intelligent systems by integrating IIoT sensors, advanced sensing schemes, and manufacturing cybersecurity.
# show_downloads: true
theme: jekyll-theme-minimal
